





inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())
inflation = int(input())